# Generated by Django 3.1.7 on 2021-03-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210308_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
